using LanguageExt.TypeClasses;

namespace CSharpKata;

/// <summary>
/// A monoid that handles log messages generated by the SearchW function
/// </summary>
/// <remarks>The LanguageExt library provides similar structures. This has 
/// been included to show how a custom structure can be used.</remarks>
internal readonly record struct Logger : Monoid<string>
{
    public string Append(string x, string y) =>
        x + y;

    public string Empty() =>
        string.Empty;
}
